version: '2'
services:
  jenkins:
    container_name: jenkins
    build: ./config/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock       
      - /usr/bin/docker:/usr/local/bin/docker
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
  reverse:
    container_name: reverse
    image: nginx
    volumes:
      - ./config/nginx/jenkins.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - jenkins
    depends_on:
      - jenkins
