version: '2'
services:
  jenkins:
    container_name: jenkins
    build: ./config/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock       
      - /usr/bin/docker:/usr/local/bin/docker
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    restart: always

  reverse:
    container_name: jenkins-reverse
    image: nginx
    volumes:
      - ./config/nginx/jenkins.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - jenkins
    depends_on:
      - jenkins
    restart: always

  php:
    container_name: jenkins-php-apache
    build: ./config/php-apache
    restart: always
    links:
      - mysql
    ports:
      - 880:80
      - 4443:443
    volumes:
      - ./data/jenkins:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /usr/bin/docker:/usr/local/bin/docker
#      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
      - ./config/php-apache/vhosts/vhosts.conf:/etc/apache2/sites-enabled/000-default.conf    
  mysql:
    build: ./config/mysql
    container_name: jenkins-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: XXXX
    volumes:
      - ./data/mysql/db:/var/lib/mysql
  
 # mongodb:
 #   image: mongo:3.2.10
 #   container_name: mongodb
 #   ports:
 #     - "27017:27017"
 #   volumes:
 #     - ./mongodb:/var/lib/mongodb
 #   restart: always 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: jenkins-phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8888:80



