version: '2'
services:
  jenkins:
    container_name: jenkins
    build: ./config/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock       
      - /usr/bin/docker:/usr/local/bin/docker
